/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author baoki
 */
public class AdBusTable extends javax.swing.JFrame {

        /**
         * Creates new form AdBusTable
         */
        public AdBusTable() {
                initComponents();
                setLocationRelativeTo(null);
                setResizable(false);
                setDefaultCloseOperation(DISPOSE_ON_CLOSE);

                loadBusData();
        }

        private void loadBusData() {
                InputStream is = getClass().getClassLoader().getResourceAsStream("db/buses.txt");
                if (is == null) {
                        System.err.println("File not found: db/buses.txt");
                        return;
                }
                System.out.println(is.toString());

                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                model.setRowCount(0); // Clear existing rows

                try (BufferedReader br = new BufferedReader(new InputStreamReader(is))) {
                        String line;
                        while ((line = br.readLine()) != null) {
                                String[] parts = line.split(" ");
                                if (parts.length == 3) {
                                        String busName = parts[0] + " " + parts[1]; // Combine "Bus" and the number
                                        int capacity = Integer.parseInt(parts[2]);
                                        model.addRow(new Object[] { busName, capacity });
                                }
                        }
                } catch (IOException | NumberFormatException e) {
                        e.printStackTrace();
                }
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                kGradientPanel1 = new keeptoo.KGradientPanel();
                jLabel1 = new javax.swing.JLabel();
                kGradientPanel4 = new keeptoo.KGradientPanel();
                jPanel3 = new javax.swing.JPanel();
                jLabel12 = new javax.swing.JLabel();
                jLabel13 = new javax.swing.JLabel();
                jTFNameBusBM = new javax.swing.JTextField();
                jTFCapacityBM = new javax.swing.JTextField();
                jBAddBus = new javax.swing.JButton();
                jBUpdateBus = new javax.swing.JButton();
                jBDeleteBus = new javax.swing.JButton();
                jLabel2 = new javax.swing.JLabel();
                jScrollPane2 = new javax.swing.JScrollPane();
                jTable1 = new javax.swing.JTable();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                kGradientPanel1.setkEndColor(new java.awt.Color(255, 204, 255));
                kGradientPanel1.setkGradientFocus(650);
                kGradientPanel1.setkStartColor(new java.awt.Color(204, 204, 255));

                jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                jLabel1.setForeground(new java.awt.Color(0, 153, 153));
                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/buss.png"))); // NOI18N
                jLabel1.setText("Bus");

                kGradientPanel4.setBorder(
                                javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
                kGradientPanel4.setForeground(new java.awt.Color(204, 204, 204));
                kGradientPanel4.setkEndColor(new java.awt.Color(255, 204, 255));
                kGradientPanel4.setkGradientFocus(1000);
                kGradientPanel4.setkStartColor(new java.awt.Color(204, 204, 255));
                kGradientPanel4.setOpaque(false);

                jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
                jPanel3.setOpaque(false);

                jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                jLabel12.setText("Name:");

                jLabel13.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
                jLabel13.setText("Capacity:");

                jBAddBus.setBackground(new java.awt.Color(0, 204, 204));
                jBAddBus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jBAddBus.setForeground(new java.awt.Color(255, 255, 255));
                jBAddBus.setText("Add");
                jBAddBus.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jBAddBusActionPerformed(evt);
                        }
                });

                jBUpdateBus.setBackground(new java.awt.Color(0, 204, 204));
                jBUpdateBus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jBUpdateBus.setForeground(new java.awt.Color(255, 255, 255));
                jBUpdateBus.setText("Update");

                jBDeleteBus.setBackground(new java.awt.Color(0, 204, 204));
                jBDeleteBus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jBDeleteBus.setForeground(new java.awt.Color(255, 255, 255));
                jBDeleteBus.setText("Delete");

                javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
                jPanel3.setLayout(jPanel3Layout);
                jPanel3Layout.setHorizontalGroup(
                                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(jPanel3Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel3Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(30, 30, 30)
                                                                                                .addComponent(jBAddBus)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                .addComponent(jBUpdateBus)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(jBDeleteBus))
                                                                                .addGroup(jPanel3Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGroup(jPanel3Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                                                false)
                                                                                                                .addComponent(jLabel12,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                Short.MAX_VALUE)
                                                                                                                .addComponent(jLabel13,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                Short.MAX_VALUE))
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                .addGroup(jPanel3Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(jTFNameBusBM,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                179,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(jTFCapacityBM,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                179,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                                .addContainerGap(41, Short.MAX_VALUE)));
                jPanel3Layout.setVerticalGroup(
                                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addGroup(jPanel3Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel12)
                                                                                .addComponent(jTFNameBusBM,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(jPanel3Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel13)
                                                                                .addComponent(jTFCapacityBM,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(jPanel3Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jBAddBus)
                                                                                .addComponent(jBUpdateBus)
                                                                                .addComponent(jBDeleteBus))
                                                                .addGap(25, 25, 25)));

                jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
                jLabel2.setForeground(new java.awt.Color(0, 153, 153));
                jLabel2.setText("BUS MANAGEMENT");

                javax.swing.GroupLayout kGradientPanel4Layout = new javax.swing.GroupLayout(kGradientPanel4);
                kGradientPanel4.setLayout(kGradientPanel4Layout);
                kGradientPanel4Layout.setHorizontalGroup(
                                kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(kGradientPanel4Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jPanel3,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                kGradientPanel4Layout.createSequentialGroup()
                                                                                .addContainerGap(
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(jLabel2)
                                                                                .addGap(64, 64, 64)));
                kGradientPanel4Layout.setVerticalGroup(
                                kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                kGradientPanel4Layout
                                                                                .createSequentialGroup()
                                                                                .addContainerGap()
                                                                                .addComponent(jLabel2)
                                                                                .addPreferredGap(
                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(jPanel3,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(45, 45, 45)));

                jTable1.setModel(new javax.swing.table.DefaultTableModel(
                                new Object[][] {
                                },
                                new String[] {
                                                "Bus Name", "Capacity"
                                }) {
                        Class[] types = new Class[] {
                                        java.lang.String.class, java.lang.Integer.class
                        };
                        boolean[] canEdit = new boolean[] {
                                        false, false
                        };

                        public Class getColumnClass(int columnIndex) {
                                return types[columnIndex];
                        }

                        public boolean isCellEditable(int rowIndex, int columnIndex) {
                                return canEdit[columnIndex];
                        }
                });
                jScrollPane2.setViewportView(jTable1);

                javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
                kGradientPanel1.setLayout(kGradientPanel1Layout);
                kGradientPanel1Layout.setHorizontalGroup(
                                kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                                                .addGap(14, 14, 14)
                                                                .addGroup(kGradientPanel1Layout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(kGradientPanel1Layout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(kGradientPanel4,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                .addComponent(jScrollPane2,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                292,
                                                                                                                Short.MAX_VALUE))
                                                                                .addComponent(jLabel1,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                90,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(12, 12, 12)));
                kGradientPanel1Layout.setVerticalGroup(
                                kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                kGradientPanel1Layout.createSequentialGroup()
                                                                                .addContainerGap()
                                                                                .addComponent(jLabel1,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                30,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(
                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                .addGroup(kGradientPanel1Layout
                                                                                                .createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                false)
                                                                                                .addComponent(jScrollPane2,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                0,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addComponent(kGradientPanel4,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                185,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addContainerGap(
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE));

                pack();
                jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                jTable1MouseClicked(evt);
                        }
                });

                jBAddBus.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jBAddBusActionPerformed(evt);
                        }
                });

                // Add an action listener to the "Update" button
                jBUpdateBus.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jBUpdateBusActionPerformed(evt);
                        }
                });
                jBDeleteBus.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jBDeleteBusActionPerformed(evt);
                        }
                });

        }// </editor-fold>//GEN-END:initComponents

        private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {
                // Get the selected row index
                int selectedRow = jTable1.getSelectedRow();

                // Retrieve data from the selected row and populate the text fields
                if (selectedRow != -1) {
                        String busName = jTable1.getValueAt(selectedRow, 0).toString();
                        String capacity = jTable1.getValueAt(selectedRow, 1).toString();

                        jTFNameBusBM.setText(busName);
                        jTFCapacityBM.setText(capacity);
                }
        }

        private void jBAddBusActionPerformed(java.awt.event.ActionEvent evt) {
                // Get data from the text fields
                String busName = jTFNameBusBM.getText().trim();
                String capacityText = jTFCapacityBM.getText().trim();

                // Validate input
                if (busName.isEmpty() || capacityText.isEmpty()) {
                        JOptionPane.showMessageDialog(this, "Please fill in all fields!", "Error",
                                        JOptionPane.ERROR_MESSAGE);
                        return;
                }

                try {
                        int capacity = Integer.parseInt(capacityText);

                        // Add the new row to the table model
                        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                        model.addRow(new Object[] { busName, capacity });

                        // Append the new bus data to the file
                        String filePath = "d:\\works\\BusManagement\\BusServiceSystem\\CSE305_BusManagement\\scr\\db\\buses.txt";
                        try (BufferedWriter writer = new BufferedWriter(new FileWriter(filePath, true))) {
                                writer.write(String.format("%s %d%n", busName, capacity));
                        }

                        JOptionPane.showMessageDialog(this, "Bus added successfully!", "Success",
                                        JOptionPane.INFORMATION_MESSAGE);

                        // Clear the text fields
                        jTFNameBusBM.setText("");
                        jTFCapacityBM.setText("");
                } catch (NumberFormatException e) {
                        JOptionPane.showMessageDialog(this, "Capacity must be a valid number!", "Error",
                                        JOptionPane.ERROR_MESSAGE);
                } catch (IOException e) {
                        JOptionPane.showMessageDialog(this, "Error writing to file: " + e.getMessage(), "Error",
                                        JOptionPane.ERROR_MESSAGE);
                }
        }

        private void jBUpdateBusActionPerformed(java.awt.event.ActionEvent evt) {
                // Get the selected row index
                int selectedRow = jTable1.getSelectedRow();

                // Ensure a row is selected
                if (selectedRow != -1) {
                        // Get updated data from the text fields
                        String updatedBusName = jTFNameBusBM.getText().trim();
                        String updatedCapacity = jTFCapacityBM.getText().trim();

                        // Validate input
                        if (updatedBusName.isEmpty() || updatedCapacity.isEmpty()) {
                                JOptionPane.showMessageDialog(this, "Please fill in all fields!", "Error",
                                                JOptionPane.ERROR_MESSAGE);
                                return;
                        }

                        try {
                                int capacity = Integer.parseInt(updatedCapacity);

                                // Update the table model
                                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                                model.setValueAt(updatedBusName, selectedRow, 0);
                                model.setValueAt(capacity, selectedRow, 1);

                                JOptionPane.showMessageDialog(this, "Row updated successfully!", "Success",
                                                JOptionPane.INFORMATION_MESSAGE);

                                // Clear the text fields
                                jTFNameBusBM.setText("");
                                jTFCapacityBM.setText("");
                        } catch (NumberFormatException e) {
                                JOptionPane.showMessageDialog(this, "Capacity must be a valid number!", "Error",
                                                JOptionPane.ERROR_MESSAGE);
                        }
                } else {
                        JOptionPane.showMessageDialog(this, "Please select a row to update!", "Error",
                                        JOptionPane.ERROR_MESSAGE);
                }
        }

        private void jBDeleteBusActionPerformed(java.awt.event.ActionEvent evt) {
                // Get the selected row index
                int selectedRow = jTable1.getSelectedRow();

                // Ensure a row is selected
                if (selectedRow != -1) {
                        // Confirm deletion
                        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this row?",
                                        "Confirm Deletion", JOptionPane.YES_NO_OPTION);
                        if (confirm == JOptionPane.YES_OPTION) {
                                // Remove the selected row from the table model
                                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                                model.removeRow(selectedRow);

                                JOptionPane.showMessageDialog(this, "Row deleted successfully!", "Success",
                                                JOptionPane.INFORMATION_MESSAGE);

                                // Clear the text fields
                                jTFNameBusBM.setText("");
                                jTFCapacityBM.setText("");
                        }
                } else {
                        JOptionPane.showMessageDialog(this, "Please select a row to delete!", "Error",
                                        JOptionPane.ERROR_MESSAGE);
                }
        }

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(AdBusTable.class.getName()).log(
                                        java.util.logging.Level.SEVERE, null,
                                        ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(AdBusTable.class.getName()).log(
                                        java.util.logging.Level.SEVERE, null,
                                        ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(AdBusTable.class.getName()).log(
                                        java.util.logging.Level.SEVERE, null,
                                        ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(AdBusTable.class.getName()).log(
                                        java.util.logging.Level.SEVERE, null,
                                        ex);
                }
                // </editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new AdBusTable().setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton jBAddBus;
        private javax.swing.JButton jBDeleteBus;
        private javax.swing.JButton jBUpdateBus;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel12;
        private javax.swing.JLabel jLabel13;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JPanel jPanel3;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JTextField jTFCapacityBM;
        private javax.swing.JTextField jTFNameBusBM;
        private javax.swing.JTable jTable1;
        private keeptoo.KGradientPanel kGradientPanel1;
        private keeptoo.KGradientPanel kGradientPanel4;
        // End of variables declaration//GEN-END:variables
}
